apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "Elysium.fullname" . }}-api
  labels:
    {{- include "Elysium.labels" . | nindent 4 }}
    app: {{ include "Elysium.fullname" . }}-api
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "Elysium.selectorLabels" . | nindent 6 }}
      app: {{ include "Elysium.fullname" . }}-api
  template:
    metadata:
      labels:
        {{- include "Elysium.selectorLabels" . | nindent 8 }}
        app: {{ include "Elysium.fullname" . }}-api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.api_image_repository }}:{{ .Values.webapi_image_tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: {{ .Chart.Name }}-api
        resources: {}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      restartPolicy: Never