trigger:
  batch: true
  branches:
    include:
    - main
    - features/*
  paths:
    exclude:
    - README.md
    - Elysium.sln

pr: 
  branches:
    include:
    - main
    - releases/*
    exclude:
    - releases/old*
  drafts: false

pool:
  vmImage: ubuntu-latest

stages:
- stage: Changes
  displayName: Has Changes
  jobs:
  - job: GetChangedFolders
    displayName: Get Changed Folders
    dependsOn: []
    steps:
    - bash: |
        curl -H 'Authorization: Bearer ${SYSTEM_ACCESSTOKEN}' ${COLLECTION_URI}${PROJECT}/_apis/build/builds/${BUILD_ID}/changes?api-version=6.0 | jq '.value[].id'
        COMMIT_IDS=`curl -H 'Authorization: Bearer ${SYSTEM_ACCESSTOKEN}' ${COLLECTION_URI}${PROJECT}/_apis/build/builds/${BUILD_ID}/changes?api-version=6.0 | jq '.value[].id'`
        CHANGED_FILES=`echo $COMMIT_IDS | xargs -I{} -L 1 git log -m -1 --name-only --pretty=format:{} | tr '\n' '|'`
        echo ${CHANGED_FILES}
        echo " ##vso[task.setvariable variable=changedFiles;isOutput=true]${CHANGED_FILES}"
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        COLLECTION_URI: $(System.CollectionUri)
        PROJECT: $(System.TeamProject)
        BUILD_ID: $(Build.BuildId)
      
- stage: BuildingAndTesting
  displayName: Building and Testing
  dependsOn:
  - Changes
  jobs:
  - job: Build_JobHost
    displayName: Build Job Build_Job
    dependsOn: []
    steps:
    - script: echo Hello, world!
  - job: Build_WebApiHost  
    displayName: Build Web Api Build_Job
    dependsOn: []
    steps:
    - script: echo Hello, world!
  - job: Build_WebAppHost
    displayName: Build Web App Build_Job
    dependsOn: []
    steps:
    - script: echo Hello, world!

- stage: UpdateHelmChartVersion
  displayName: Update the Helm Chart Version
  jobs:
  - job: UpdateHelmChartVersion
    steps:
    - script: echo Hello, world!
