trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '217940c9-14ba-45ce-9481-1d5ec26d7c35'
  containerRegistry: 'containerdemos.azurecr.io'
  tag: '$(Build.BuildId)'
  # Dockerfiles to build
  buildJob: 'false'
  buildWebApi: 'false'
  buildWebApp: 'false'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: DetectChanges
  displayName: Detect code changes
  jobs:
  - job: Detect
    pool: 
      vmImage: $(vmImageName)
    steps:
    - pwsh: |
        $files=$(git diff HEAD HEAD~ --name-only)
        foreach($f in $files) {
          switch -regex ($f) {
            "Elysium.Job.Host/" {
              Write-Host "##vso[task.setvariable variable=buildJob]$true"
            }
            "Elysium.WebApiHost/" {
              Write-Host "##vso[task.setvariable variable=buildWebApi]$true"
            }
            "Elysium.WebAppHost/" {
              Write-Host "##vso[task.setvariable variable=buildWebApp]$true"
            }
          }
        }
    - pwsh: |
        write-Output $(buildJob)
        write-Output $(buildWebApi)
        write-Output $(buildWebApp)
- stage: Build
  condition: eq(false,true) 
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
