trigger:
  batch: true
  branches:
    include:
    - main
    - features/*
  paths:
    exclude:
    - README.md
    - Elysium.sln

pr: 
  branches:
    include:
    - main
    - releases/*
    exclude:
    - releases/old*
  drafts: false

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildingAndTesting
  displayName: Building and Testing
  jobs:
  - job: GetChangedFolders
    displayName: Get Changed Folders
    dependsOn: []
    steps:
    - bash: echo    
          | echo curl -H 'Authorization: Bearer ${SYSTEM_ACCESSTOKEN}' ${COLLECTION_URI}/${PROJECT}/_apis/build/builds/${BUILD_ID}/changes?api-version=6.0
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        COLLECTION_URI: $(System.CollectionUri)
        PROJECT: $(System.TeamProject)
        BUILD_ID: $(Build.BuildId)

  - job: Build_JobHost
    displayName: Build Job Build_Job
    dependsOn: 
    - GetChangedFolders
    steps:
    - script: echo Hello, world!
  - job: Build_WebApiHost  
    displayName: Build Web Api Build_Job
    dependsOn:
    - GetChangedFolders
    steps:
    - script: echo Hello, world!
  - job: Build_WebAppHost
    displayName: Build Web App Build_Job
    dependsOn:
    - GetChangedFolders
    steps:
    - script: echo Hello, world!
- stage: UpdateHelmChartVersion
  displayName: Update the Helm Chart Version
  dependsOn:
  - BuildingAndTesting
  jobs:
  - job: UpdateHelmChartVersion
    steps:
    - script: echo Hello, world!
