parameters:
- name: forceBuild
  displayName: Force Builds?
  default: false
  type: boolean

trigger:
  batch: false
  branches:
    include:
    - main
    - features/*
  paths:
    exclude:
    - README.md
    - Elysium.sln

pr: 
  branches:
    include:
    - main
    - releases/*
    exclude:
    - releases/old*
  drafts: false

pool:
  vmImage: ubuntu-latest

stages:
- stage: Changes
  displayName: Has Changes
  jobs:
  - job: Changes
    displayName: Get Changed Folders
    dependsOn: []
    steps:
    - bash: |
        COMMIT_IDS=`curl -H 'Authorization: Bearer ${SYSTEM_ACCESSTOKEN}' ${COLLECTION_URI}${PROJECT}/_apis/build/builds/${BUILD_ID}/changes?api-version=6.0 | jq '.value[].id' | tr ' ' '\n'`
        echo ${COMMIT_IDS} | tr ' ' '\n'
        CHANGED_FILES=`echo $COMMIT_IDS | xargs -L 1 git log -m -1 --name-only --pretty=format:| tr '\n' '|'`
        echo ${CHANGED_FILES}
        echo " ##vso[task.setvariable variable=Changes;isOutput=true]${CHANGED_FILES}"
      name: Changes
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        COLLECTION_URI: $(System.CollectionUri)
        PROJECT: $(System.TeamProject)
        BUILD_ID: $(Build.BuildId)
      
- stage: BuildingAndTesting
  displayName: Building and Testing
  #condition: or(contains(variables.Changes, 'src/'), ${{ parameters.forceBuild }})
  variables:
  - name: Changes
    value: $[ stageDependencies.Changes.Changes.outputs['Changes.Changes'] ]
  dependsOn:
  - Changes
  jobs:
  - job: Build_JobHost
    displayName: Build Job Build_Job
    dependsOn: []
    #condition: or(contains(variables.Changes, 'Job.'), ${{ parameters.forceBuild }})
    steps:
    - bash: echo $(Changes)
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'anbossar-training-subscription(8b25cfae-660b-4066-9ce5-0858e9ab3eac)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login -n anbossar
          docker buildx build --platform linux/amd64 -f Job.Dockerfile -t anbossar.azurecr.io/elysium/job:latest -t anbossar.azurecr.io/elysium/job:branch --push .
        workingDirectory: 'src'
    - bash: echo Hello, world! ${SHOULD} ${IS} ${VARIA}
      env:
        SHOULD: $(Changes)
        VARIA: $[ variables['Changes'] ]
        IS:  $[ contains(variables['Changes'], '.yml') ]
  - job: Build_WebApiHost
    condition: or(contains(variables['Changes'], 'WebApi.'), contains(variables['Changes'], 'Library'), ${{ parameters.forceBuild }})
    displayName: Build Web Api Build_Job
    dependsOn: []
    steps:
    - script: echo Hello, world!
  - job: Build_WebAppHost
    condition: contains(variables['Changes'], 'WebApp.')
    displayName: Build Web App Build_Job
    dependsOn: []
    steps:
    - script: echo Hello, world!

- stage: UpdateHelmChartVersion
  displayName: Update the Helm Chart Version
  condition: contains(variables['Changes'], 'charts/')
  variables:
  - name: Changes
    value: $[ stageDependencies.Changes.Changes.outputs['Changes.Changes'] ]
  dependsOn:
  - Changes
  jobs:
  - job: UpdateHelmChartVersion
    steps:
    - script: echo Hello, world!
